name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  CI: true
  GHUB_Accesstoken: ${{ secrets.GHUB_ACCESSTOKEN }}
  GHUB_InvalidAccesstoken: ${{ secrets.GHUB_INVALIDACCESSTOKEN }}
  GITHUB_baseurl: https://api.github.com
  GHUB_USERNAME: ${{ secrets.GHUB_USERNAME }}
  GHUB_PASSWORD: ${{ secrets.GHUB_PASSWORD }}
  OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
  OPENWEATHER_BASE_URL: https://api.openweathermap.org/data/2.5
  API_KEY: ${{ secrets.API_KEY }}
  API_KEY_HEADER: x-api-key
  API_KEY_QUERY: apikey
  ECHO_BASE_URL: https://postman-echo.com
  API_KEY_invalid: demo
  INVALID_OPENWEATHER_API_KEY: ${{ secrets.INVALID_OPENWEATHER_API_KEY }}
  id: 524901
  City: Bangalore
  language: fr

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run all tests
        run: npx playwright test
      - name: Upload Report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
